Solicitud de alejcg para la legion
AleCga56/legion-del-mal pull request #1
Opened 2018-05-22 22:20 UTC by AlejCG

### Modificaciones
Borre al espantapajaros

### Adiciones
Aplicando a la legión del mal

2018-05-22 23:28 UTC, AleCga56 requested changes
Por favor no borren al espantapájaros

2018-05-22 23:28 UTC, AleCga56 commented on miembros.md
> -23. Scarecrow
No quiero que borren al espantapajaros

2018-05-28 15:59 UTC, AlejCG commented
Esta bien no lo voy a borrar

2018-05-28 15:59 UTC, AlejCG commented
Esta bien no lo voy a borrar

2018-05-28 16:10 UTC, AlejCG commented on miembros.md
> -23. Scarecrow
Esta bien no lo voy a borrar

2018-05-28 18:16 UTC, AleCga56 approved these changes
Ok esto esta correcto

2018-05-28 18:32 UTC, merged